Repository ca-api-gateway/gateway-export-plugin, pull requests merged in 2018-10, with the labels that each got.

#27 Merge exported contents into existing files
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundleTask.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/Bundle.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/entity/ListenPortEntity.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/loader/ListenPortLoader.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/EncassWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/EnvironmentPropertiesWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/IdentityProviderWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/JdbcConnectionWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/ListenPortWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/PolicyBackedServiceWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/ServiceWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/TrustedCertWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/WriterHelper.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/BindOnlyLdapIdentityProviderDetail.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/Encass.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/EncassParam.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/IdentityProvider.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/IdentityProviderDetail.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/LdapIdentityProviderDetail.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/ListenPort.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/PolicyBackedService.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/PolicyBackedServiceOperation.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/file/DocumentFileUtils.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/json/JsonTools.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/properties/OrderedProperties.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/xml/DocumentUtils.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/WriterHelperTest.java
  src/test/resources/config/test-file.json
  src/test/resources/config/test-file.yml
  src/test/resources/config/testProperties.properties
Labels: in progress, ready for review

#28 Bug: TrustedCert is missing default constructor
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/TrustedCert.java
Labels: ready for review

#29 Adding support for private keys
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/Bundle.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/BundleElementNames.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/entity/KeyStoreType.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/entity/PrivateKeyEntity.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/BundleFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/loader/PrivateKeyLoader.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/PrivateKeyWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/TrustedCertWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/PrivateKey.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/export/BuildExportQueryTask.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/file/DocumentFileUtils.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/gateway/CertificateUtils.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/http/GatewayClient.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/injection/ExportPluginModule.java
Labels: in progress, ready for review

#30 Autogenerating the Gradle Plugin Metadata files
  build.gradle
  src/main/resources/META-INF/gradle-plugins/com.ca.apim.gateway.gateway-export-plugin-base.properties
  src/main/resources/META-INF/gradle-plugins/com.ca.apim.gateway.gateway-export-plugin.properties
Labels: in progress

#32 Do not create entity file if there are no entities of a certain type
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/WriterHelper.java
Labels: in progress, ready for review

#34 build master branch only
  .travis.yml
Labels: in progress

#33 PrivateKeys: Skipping export of the certificates
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/PrivateKeyWriter.java
Labels: in progress

#35 Fix exporting private keys
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/entity/KeyStoreType.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/BundleFilter.java
Labels: in progress

#36 Explicitly List Entities to Export
  README.md
  src/main/java/com/ca/apim/gateway/cagatewayexport/CAGatewayExport.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/GatewayExportPluginConfig.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundle.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundleTask.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/Bundle.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/entity/FolderTree.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/entity/IdentityProviderEntity.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/BundleFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/EntityFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/EntityFilterException.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/EntityFilterRegistry.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/FilterConfiguration.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/ClusterPropertyFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/EncassFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/FolderFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/IdentityProviderFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/JDBCConnectionFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/ListenPortFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/PolicyBackedServiceFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/PolicyFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/PrivateKeyFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/ServiceFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/StoredPasswordFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/TrustedCertificateFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/PolicyWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/gateway/DependencyUtils.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/injection/ExportPluginModule.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/CAGatewayExportTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/ExplodeBundleTaskTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/BundleFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/EntityFiltersTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/ClusterPropertyFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/EncassFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/FilterTestUtils.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/FolderFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/IdentityProviderFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/JDBCConnectionFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/ListenPortFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/PolicyBackedServiceFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/PolicyFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/PrivateKeyFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/ServiceFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/StoredPasswordFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/TrustedCertificateFilterTest.java
  src/test/resources/bundles/environment-properties-test.bundle
Labels: in progress, ready for review

#37 Adding cassandra connections
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/BundleElementNames.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/bundle/entity/CassandraConnectionEntity.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/CassandraConnectionFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/StoredPasswordFilter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/CassandraConnectionLinker.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/loader/CassandraConnectionLoader.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/CassandraConnectionWriter.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/beans/CassandraConnection.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/xml/DocumentToolsException.java
  src/main/java/com/ca/apim/gateway/cagatewayexport/util/xml/DocumentUtils.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/filter/entityfilters/CassandraConnectionFilterTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/linker/CassandraConnectionLinkerTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/loader/CassandraConnectionLoaderTest.java
  src/test/java/com/ca/apim/gateway/cagatewayexport/tasks/explode/writer/CassandraConnectionWriterTest.java
Labels: in progress
